---
# tasks file for ssh

- block:
    - name: configure | ssh keys
      user: name="{{ ansible_user_id }}"
            generate_ssh_key=yes ssh_key_bits="{{ ssh_key_bits }}"
            ssh_key_comment="{{ ssh_key_comment }}"

    - name: setup | ssh config
      file: path="{{ ansible_user_dir }}/.ssh/config" state=touch

    - name: configure | ssh config
      ssh_config: host="{{ item.key }}"
                  user="{{ ansible_user_id }}"
                  remote_user="{{ item.value.user }}"
                  hostname="{{ item.value.hostname }}"
      with_dict: "{{ hosts }}"
  tags:
    - bootstrap
    - configure
    - update
