---
galaxy_info:
  author: mwilliammyers
  description: "Install & configure ansible."
  license: GPLv3
  min_ansible_version: 2.0
  platforms:
    - name: GenericUNIX
      versions:
        - all
        - any
    - name: GenericBSD
      versions:
        - all
        - any
    - name: GenericLinux
      versions:
        - all
        - any
  galaxy_tags:
    - development
    - ansible

dependencies: []
